language: ruby

rvm:
- 2.3.0

before_script:
- chmod +x ./script/cibuild

script: "./script/cibuild"

branches:
  only:
  - master

deploy:
  provider: s3
  access_key_id: AKIAI5E6FVPYHNOBRK4A
  secret_access_key:
    secure: H8p2JO82Bg9ipQVSsxntgW59KLf2qGdypeSyqD65Qh23Sd8BDn9WlyJgQjfGtQVDnsME4Mky3N15dHsEuJQEMv7kDLQlllyBIMqB4S7KxNa267CQt/2b4bvfNv9xIfkv1+3JiWzXAaNKSa96xXvklP3kzuFglOz3BtqW83qpWGwF0DVBZBf1Ut/Rye/BIB3VDN0gTBWURrrjDuAgM+zj0WX8NX0c1U3CirPmgZ7UmYVTlswDxQWzZG/AwYI2eZPWzv6nGtyLK+/ihNSz5SEotqcmKdBrQLpYvzuxpjEDyqehgFHQIYIE08xuIa4nvQ3+UhOnin/hwEJ5MEGAtV/gH8Jl7Yk+GM7r9gROZ8LdSx4wnoXP9Ni8drfWcErzixSV9jjeD9bFOGf3VZNvF1wXrd9jN3ZNJjP783f6LQep65PpLEdJ6L/2qyIOUWFg9SqHoFmszNY8HBxC7dwmuWpwePBt39NbUuaDyQgpKZrh7WPM3yMvTeL9l8uOUDcQy+zXGHY6kysuPlKpyrk32eitTzbKMMYFkx5Fc+kPSNZtJ4iNUtNt/wBtLzQhjfVUp6d7xd4jTg7SmcZn+4bn0QaAlZhvzZ1oPlOAOG0dXNI07rWLul9YEESVmC0r+bJpvJp4gFwbzQzwCHZuz4EVwywCa6eYWzLUob1LJmg47m+AGJc=
  bucket: www.npsoftware.co.uk
  local_dir: _site
  skip_cleanup: true
  acl: public_read
  on:
    branch: master
